### ISSUE TITLE
Cannot mkdir in Windows

### ISSUE THREAD

**Issue by maximusprimate** [Joao-Peterson/super-figure#1]
I get the following error in Windows after selecting text `fig/text`, bringing up the command pallet, selecting  `Super Figure: Insert vector figure as latex snippet` and choosing the template `~/.config/super-figure/templates/template.svg` which does indeed exist.

`Could not copy template file 'C:\Users\[myusername]/.config/super-figure/templates/template.svg'. Os Error: Error: ENOENT: no such file or directory, mkdir '\\?\C:\c:\[path-to-my-project]\fig'`

The only extension settings that I have changed are the paths to Inkscape and Gimp, which are `"C:\Program Files\Inkscape\bin\inkscape.exe"` and `"C:\Program Files\GIMP 2\bin\gimp-2.10.exe"`, respectively.

**Comment by Joao-Peterson** [comment]
Seems like the target image file is kinda messed up. Mind providing the log in the `console > output > Super Figure`?

**Comment by maximusprimate** [comment]
I'm afraid I don't know how to do that.  Do you want me to run your extension on its own? Otherwise the debug console is set for tex.

**Comment by maximusprimate** [comment]
Editing vector figure: fig/test
File 'fig/test.svg' doesn't exists, using template '~/.config/super-figure/templates/template.svg'
Copying from: 'C:\Users\[myuserneame]/.config/super-figure/templates/template.svg' to: 'C:\c:\[path-to-my-project]\fig\test.svg'
Could not copy template file 'C:\Users\[myusername]/.config/super-figure/templates/template.svg'. Os Error: Error: ENOENT: no such file or directory, mkdir '\\?\C:\c:\[path-to-my-project]\fig'

**Comment by maximusprimate** [comment]
Yeah, it looks like there are two references to C drive.  If I try to run this in a different drive, say G, then it'll give me a similar message: 
`Copying from: 'C:\Users\[myuserneame]/.config/super-figure/templates/template.svg' to: 'C:\g:\[path-to-my-project]\fig\test.svg'`

**Comment by Joao-Peterson** [comment]
I will have a look at it and test it on a Windows machine in a hour, maybe tomorrow

**Comment by Joao-Peterson** [comment]
Good to go, tested on linux and windows. If you found any other problem let me know. Cheers, happy holidays!

**Comment by maximusprimate** [comment]
Thanks for the quick fix!  I'm really enjoying using this.  RIP Castel!
