### ISSUE TITLE
Cannot copy to desired directory

### ISSUE THREAD

**Issue by maximusprimate** [Joao-Peterson/super-figure#3]
In Windows it seems like Super Figure copies the template to the root folder that VSCode has opened, and not the directory of the tex file being edited.  So if I am editing file `vscode-folder/latex-folder/file.tex` then running Super Figure inside `file.tex` on text `fig` will copy the template to `vscode-folder/fig.svg` instead of `vscode-folder/latex-folder/fig.svg`.

I'm not sure if that's the intended behaviour, but I think it would make more sense for the template to be copied to the same directory as the tex file that's being edited.  Super Figure works as intended if your tex file is in the root of the VSCode folder, but not anywhere else.

I wonder if it's in the definition of `${dir}`?

**Comment by Joao-Peterson** [comment]
That's intended behavior, i opted to use the workspace folder as the relative directory for executing commands and copying files.

If you want to create an image, say in `vscode-folder/latex-dir/images/fig`, then it is simple as write it down as such, but you wouldn't be able to compile latex as usual, so i prefer to just open the latex folder in itself. Maybe i should emphasize that better in the README.

Well, it was easier to code in this way and more intuitive, at least to me, sorry but this is the way i would like things to work.

**Comment by maximusprimate** [comment]
That's too bad.  I wonder how hard it would be to make the adjustment to copy the files into the directory of the tex file.  Doing so wouldn't interfere with its current functionality.

**Comment by Joao-Peterson** [comment]
What can be done is a option for a relative folder, so if edit the tex file `vscode-folder/latex-folder/file.tex` and i would want to save the images to the folder `vscode-folder/latex-folder/images/`, then

**Comment by maximusprimate** [comment]
That's interesting.  I'll try that out!

**Comment by Joao-Peterson** [comment]
Try what? that's not a option at this time. Or are you gonna make a PR?

If not i will try and make time this next week and program this option.

**Comment by maximusprimate** [comment]
I misunderstood - I thought you had already implemented this.  I won't be able to make a PR at this time since I am still grappling with how vscode extensions are built.
