### ISSUE TITLE
Inkscape doesn't recognize the file type

### ISSUE THREAD

**Issue by jer-myjohn** [Joao-Peterson/super-figure#4]
I get the following message from Inkscape when trying to insert a new figure:

"Could not detect file format. Tried to open it as an SVG anyway but this also failed."

I think this might have to do with `super-figure.vectorFigureEditorArgs` not being setup for me; what am I supposed to do to set this up?

Also, is there anything I am supposed to set up in Inkscape because I am getting an error `LaTeX Error: File figures/figsvg1.pdf_tex not found.` Note `figures` is the folder, and `figsvg1` is the svg file and I am using LaTeX Workshop and Tex Live. 

Apologies if there is something obvious I am missing, I am brand new to using VS Code and LaTeX.

**Comment by jer-myjohn** [comment]
Settings:
`"super-figure.vectorFigureEditor": "C:/Program Files/Inkscape/bin/inkscape.exe",`
`"super-figure.bitmapFigureEditor": "C:/Users/iamje/AppData/Local/Programs/GIMP 2/bin",`
`"super-figure.bitmapFigureEditorArgs": "${file}",`
`"super-figure.bitmapFileExt": "png,jpeg,jpg,gif,tiff,bmp,xcf",`
`"super-figure.bitmapTemplate": "~/.config/super-figure/templates/template.xcf",`
`"super-figure.onBitmapFileSave": "${executable} -n -i -b '(let* ( (filename \"${file}\") (fileout \"${dir}/${basename}.png\") (image 0) (layer 0) ) (set! image (car (gimp-file-load RUN-NONINTERACTIVE filename filename))) (set! layer (car (gimp-image-merge-visible-layers image CLIP-TO-IMAGE))) (gimp-file-save RUN-NONINTERACTIVE image layer fileout fileout) (gimp-image-delete image) (gimp-quit 0))'",`
`"super-figure.onVectorFileSave": "${executable} ${file} --export-area-page --export-dpi 300 --export-type=pdf --export-latex --export-filename ${dir}/${basename}.pdf",`
`"super-figure.vectorFigureEditorArgs": "${file}",`
`"super-figure.vectorFileExt": "eps,svgz,pdf,ps,ai,odg",`
`"super-figure.vectorTemplate": "~/.config/super-figure/templates/template.svg",`

From VS Code Latex Workshop:
[{
	"resource": "/g:/My Drive/SP23/PHYS 207/Notes/notes.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "File `figures/figsvg1.pdf_tex' not found.\n",
	"source": "LaTeX",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 65536
},{
	"resource": "/g:/My Drive/SP23/PHYS 207/Notes/notes.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Undefined control sequence.\n\\incsvg ...svgwidth {\\columnwidth } \\graphicspath \n",
	"source": "LaTeX",
	"startLineNumber": 50,
	"startColumn": 1,
	"endLineNumber": 50,
	"endColumn": 65536
},{
	"resource": "/g:/My Drive/SP23/PHYS 207/Notes/notes.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Emergency stop.\n<read *> \n",
	"source": "LaTeX",
	"startLineNumber": 50,
	"startColumn": 1,
	"endLineNumber": 50,
	"endColumn": 65536
},{
	"resource": "/g:/My Drive/SP23/PHYS 207/Notes/notes.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": " ==> Fatal error occurred, no output PDF file produced!\nTranscript written on notes.log.\nLatexmk: Getting log file 'notes.log'\nLatexmk: Examining 'notes.fls'\nLatexmk: Examining 'notes.log'\nLatexmk: Errors, so I did not complete making targets\nCollected error summary (may duplicate other messages):\n",
	"source": "LaTeX",
	"startLineNumber": 50,
	"startColumn": 1,
	"endLineNumber": 50,
	"endColumn": 65536
},{
	"resource": "/g:/My Drive/SP23/PHYS 207/Notes/notes.tex",
	"owner": "latex",
	"severity": 4,
	"message": "[chktex] 24: Delete this space to maintain correct pagereferences.",
	"startLineNumber": 51,
	"startColumn": 8,
	"endLineNumber": 51,
	"endColumn": 9
}]

From CMD:

** (org.inkscape.Inkscape:29068): WARNING **: 09:53:48.925: Can't open file: g:\My (doesn't exist)

** (org.inkscape.Inkscape:29068): WARNING **: 09:54:07.988: Can't open file: g:\My (doesn't exist)
ink_file_open: 'g:\My' cannot be opened!
InkscapeApplication::document_open: Failed to open: g:\My
ConcreteInkscapeApplication::on_open: failed to create document!

** (org.inkscape.Inkscape:29068): WARNING **: 09:54:07.993: Can't open file: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS (doesn't exist)

** (org.inkscape.Inkscape:29068): WARNING **: 09:54:09.563: Can't open file: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS (doesn't exist)
ink_file_open: 'C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS' cannot be opened!
InkscapeApplication::document_open: Failed to open: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS
ConcreteInkscapeApplication::on_open: failed to create document!

** (org.inkscape.Inkscape:29068): WARNING **: 09:54:09.574: Can't open file: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg (doesn't exist)

** (org.inkscape.Inkscape:29068): WARNING **: 09:54:09.578: Can't open file: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg (doesn't exist)
ink_file_open: 'C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg' cannot be opened!
InkscapeApplication::document_open: Failed to open: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg
ConcreteInkscapeApplication::on_open: failed to create document!
ink_file_open: 'g:\My' cannot be opened!
InkscapeApplication::document_open: Failed to open: g:\My
ConcreteInkscapeApplication::on_open: failed to create document!
ink_file_open: 'C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS' cannot be opened!
InkscapeApplication::document_open: Failed to open: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\Drive\SP23\PHYS
ConcreteInkscapeApplication::on_open: failed to create document!
ink_file_open: 'C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg' cannot be opened!
InkscapeApplication::document_open: Failed to open: C:\Users\iamje\AppData\Local\Programs\Microsoft VS Code\207\Notes\figures\figsvg1.svg
ConcreteInkscapeApplication::on_open: failed to create document!

(org.inkscape.Inkscape:29068): Gtk-WARNING **: 09:57:06.232: Negative content width -11 (allocation 1, extents 0x12) while allocating gadget (node box, owner gtkmm__GtkBox)

(org.inkscape.Inkscape:29068): Gtk-WARNING **: 09:57:06.239: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 28

(org.inkscape.Inkscape:29068): Gdk-CRITICAL **: 09:57:06.245: gdk_window_move_resize_internal: assertion 'GDK_IS_WINDOW (window)' failed

Another thing, I can open the svg file just fine with Inkscape by myself

**Comment by Joao-Peterson** [comment]
Hummmm, iteresting, i want to look at your debug output for the Super figure extension, not just the Latex workshop one, would you mind redoing your normal workflow and uploading the console debug?

I think spaces on the paths might be the cause of the problem, as we can see inkscape failing to open:

```
** (org.inkscape.Inkscape:29068): WARNING **: 09:54:07.988: Can't open file: g:\My (doesn't exist)
ink_file_open: 'g:\My' cannot be opened!
InkscapeApplication::document_open: Failed to open: g:\My
ConcreteInkscapeApplication::on_open: failed to create document!`
```

**Comment by jer-myjohn** [comment]
I think you were right, I was trying to store it on the cloud using google drive, but the path for that include "My Drive", which has a space. I tried a local environment and it worked as described; no issues! Thank you for making this plugin!

**Comment by Joao-Peterson** [comment]
That's great to hear! but i think this is a relevant issue, please again, do you mind providing the vscode log for the Super figure extension while you are trying to edit a file in your cloud drive? It's gonna help me figure out what can be done this issue.

**Comment by jer-myjohn** [comment]
log:
Super figure extension activated
Executable for vector images: 'C:/Program Files/Inkscape/bin/inkscape.exe'
Executable for bitmap images: 'C:/Users/iamje/AppData/Local/Programs/GIMP 2/bin/gimp-2.10.exe'
Editing vector figure: figure/image1
File 'figure/image1.svg' doesn't exists, using template '~/.config/super-figure/templates/template.svg'
Copying from: '\Users\iamje\.config\super-figure\templates\template.svg' to: 'g:\My Drive\SP23\PHYS-207\figure\image1.svg'
Launching: '"C:/Program Files/Inkscape/bin/inkscape.exe" g:\My Drive\SP23\PHYS-207\figure\image1.svg'

So it looks like everything is doing what it's supposed to do as far as the extension is concerned. Apparently the white space in "My Drive" is a know issue for paths when using Google Drive File Stream.

**Comment by Joao-Peterson** [comment]
There was a mistake in my execute call, there was missing quotes around the filename, thus inkscape could not open the file. All good now!

**Comment by ZeyuSun** [comment]
I had the same error, but I made it work by manually adding double quotes around ${file}.
![image](https://github.com/user-attachments/assets/e7aab713-b3dd-4a5f-901b-80f9178702f7)
