### ISSUE TITLE
Changing the file's name

### ISSUE THREAD

**Issue by sleepymalc** [Joao-Peterson/super-figure#5]
This seems like an interesting project since it works for windows as well for editing. Though I personally use a mac, and have configured Gilles' setup in this [repo](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape), I'm missing one important functionality: renaming a figure. 

Since by exporting to `pdf_latex` from inkscape, there are three files for an image, changing them manually is quite painful. I'm wondering whether this project address this issue. I don't think Gilles had thought about it before.

**Comment by Joao-Peterson** [comment]
First, let me say that your setup is very cool, and the repo is amazing, i learned a lot. And just like Gilles i didn't think of that hahahaha.

I will mark this as a feature and maybe next week i'll have time to implement it.

Thanks for the suggestion, and again, nice setup @sleepymalc

**Comment by sleepymalc** [comment]
Yea, thanks! I'm quite busy rn, but I'm interested to see the solution.

**Comment by Joao-Peterson** [comment]
Feature added! on the commit 7081f79605d938931fe30b31e8b547b2212a65d6.
Thanks for the suggestion.
