### ISSUE TITLE
Windows OnSave

### ISSUE THREAD

**Issue by wohlersgit** [Joao-Peterson/super-figure#7]
When saving a inkscape file on Windows 11, the generated command to export the file doesn't work. with the file test.svg in the folder img it generates a command like:

""c:\...\inkscape.exe"" "c:\...\img\test.svg" --export-area-page ... --export-filename "c:\...\img"/"test".pdf

while it should generate:
"c:\...\inkscape.exe" "c:\...\img\test.svg" --export-area-page ... --export-filename "c:\...\img/test.pdf"

so the Variable from the executable has to many quotation marks and when the variables for the Directory and Filename get's joined there is also an error with the quotation marks, because they should only be at the beginning at very end.

**Comment by wohlersgit** [comment]
I think i also found a solution, inside the vars.ts file remove the 'wrapQuotes' function, so you can manually add them in the extension settings, i wanted to change this myself, but sadly i didn't managed to pack the source to a vsix file...

**Comment by Joao-Peterson** [comment]
nice catch! right know i occupied with other stuff, but soon i will change this and other issues. Thanks for the issue!

**Comment by Joao-Peterson** [comment]
Removed the quotes, tested and working on linux and windows! Thanks again and sorry for the wait
